docker:
  build:
  workdir: /test
scripts:
  start: ls
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: bookstore-tests-rspec
    operations:
      - op: replace
        path: type
        value: job
      - op: replace
        path: scripts.start
        value: bundle exec rspec
  - name: bookstore-tests-tailf
    operations:
      - op: replace
        path: scripts.start
        value: tail -f /dev/null