docker:
  build:
  workdir: /test
scripts:
  start: ls
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: bookstore-tests-as-job
    operations:
      - op: replace
        path: type
        value: job