docker:
  build:
  workdir: /test
scripts:
  start: ./start.sh
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: target-docker
    operations:
      - op: add
        path: build_target
        value: docker
  - name: target-kubernetes
    operations:
      - op: replace
        path: type
        value: job
      - op: add
        path: build_target
        value: kubernetes