docker:
  build:
  workdir: /test
scripts:
  start: tail -f /dev/null
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: bookstore-tests-rspec
    operations:
      - op: replace
          path: type
          value: job
      - op: replace
        path: scripts.start
        value: bundle exec rspec