docker:
  build:
  workdir: /test
scripts:
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: bookstore-tests-rspec
    operations:
      - op: replace
        path: type
        value: job
      - op: add
        path: scripts.start
        value: bundle exec rspec
  - name: bookstore-tests-tailf
      operations:
        - op: add
          path: scripts.start
          value: tail -f /dev/null