docker:
  build:
  workdir: /test
scripts:
  start: sleep 20; bundle exec rspec
  ls: ls
  parameterized: .testbox/parameterized.sh
patches:
  - name: bookstore-api-tests
    operations:
      - op: replace
        path: type
        value: job
