docker:
  build:
  workdir: /test
scripts:
  start: ./start.sh
  ls: ls
  parameterized: .testbox/parameterized.sh
faketime: true
patches:
  - name: bookstore-tests-as-job
    operations:
      - op: replace
        path: type
        value: job
